name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        # os: [ubuntu-22.04, windows-2022, macos-11]

    steps:
      - name: Checkout imagedata_registration
        uses: actions/checkout@v4

      - name: Build wheels
        # uses: pypa/cibuildwheel@v2.16.1
        env:
          # Skip 32-bit builds
          # Disable building PyPy wheels on all platforms
          # Skip all musllinux (manylinux only supported by itk-io)
          CIBW_SKIP: "*-win32 *-manylinux_i686 pp* *-musllinux*"
          NPY_NO_DEPRECATED_API: "NPY_1_7_API_VERSION"
          
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"
        run: |
          pip install cython numpy
          mkdir -p imagedata_registration/NPreg
          python setup.py build_ext -i
          mv imagedata_registration/NPreg/*.so src/imagedata_registration/NPreg
          bash build_tools/wheels/build_wheels.sh

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
      - name: File list
        run: |
          pwd
          ls -lR
      - name: build_tools/wheels/build_wheels.sh
        run: |
          cat build_tools/wheels/build_wheels.sh
